// @ts-ignore missing description for agent guardrails
const unsafeValue = {} as any;
const doubleAsserted = unsafeValue as unknown as string;
const generated = "AI generated by helper";

it.skip("skips validation", () => {
	expect([unsafeValue, doubleAsserted, generated]).toBeDefined();
});
